# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: CMS
  licenses: Apache-2.0
  images: |
    - name: nginx-exporter
      image: docker.io/bitnami/nginx-exporter:1.4.1-debian-12-r5
    - name: os-shell
      image: docker.io/bitnami/os-shell:12-debian-12-r37
    - name: wordpress-nginx
      image: docker.io/bitnami/wordpress-nginx:6.7.2-debian-12-r0
apiVersion: v2
appVersion: 6.7.2
dependencies:
- condition: memcached.enabled
  name: memcached
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 7.x.x
- condition: mariadb.enabled
  name: mariadb
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 20.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: WordPress is the world's most popular blogging and content management platform. Powerful yet simple, everyone from students to global corporations use it to build beautiful, functional websites. This Chart uses the -nginx variant of the wordpress container.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/wordpress/img/wordpress-stack-220x234.png
keywords:
- application
- blog
- cms
- http
- php
- web
- wordpress
- nginx
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: wordpress-nginx
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/wordpress-nginx
version: 24.1.11
