{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if or .Values.customPostInitScripts .Values.wordpressConfigureCache }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-postinit" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- if .Values.wordpressConfigureCache }}
  {{- $cacheFullname := include "wordpress.cacheHost" . }}
  {{- $cachePort := include "wordpress.cachePort" . | int }}
  {{- $cacheType := include "wordpress.cacheType" . }}
  00-configure-w3-total-cache.sh: |-
    #!/bin/bash

    # Add permissions to edit wp-config.php
    chmod +w /emptydir/app-base-dir/wp-config.php

    # Activate W3 Total Cache pairs
    wp plugin activate w3-total-cache
    wp total-cache fix_environment

    wp total-cache option set dbcache.engine {{ $cacheType }} --type=string
    wp total-cache option set objectcache.engine {{ $cacheType }} --type=string
    wp total-cache flush all
    wp total-cache option set dbcache.{{ $cacheType }}.servers {{ $cacheFullname }}:{{ $cachePort }} --type=string
    wp total-cache option set dbcache.enabled true --type=boolean
    wp total-cache option set objectcache.{{ $cacheType }}.servers {{ $cacheFullname }}:{{ $cachePort }} --type=string
    wp total-cache option set objectcache.enabled true --type=boolean
    wp total-cache flush all

    # Revoke permissions to edit wp-config.php
    chmod a-w /emptydir/app-base-dir/wp-config.php
  {{- end }}
  {{- if .Values.customPostInitScripts }}
  {{- include "common.tplvalues.render" (dict "value" .Values.customPostInitScripts "context" $) | nindent 2 }}
  {{- end }}
{{- end }}
